_target_: src.architectures.huggingface_architecture.HuggingFaceArchitecture

model:
  _target_: src.architectures.models.huggingface_model.HuggingFaceModel
  pretrained_model_name: ${pretrained_model_name}
  is_causal: ${is_causal}
  is_preprocessed: ${is_preprocessed}
  custom_data_encoder_path: ${custom_data_encoder_path}
  precision: ${precision}
  mode: ${mode}
  quantization_type: ${quantization_type}
  quantization_config:
    _target_: transformers.BitsAndBytesConfig
    load_in_4bit: ${quantization_config.load_in_4bit}
    bnb_4bit_quant_type: ${quantization_config.bnb_4bit_quant_type}
    bnb_4bit_use_double_quant: ${quantization_config.bnb_4bit_use_double_quant}
    bnb_4bit_compute_dtype: ${quantization_config.bnb_4bit_compute_dtype}
  peft_type: ${peft_type}
  peft_config:
    _target_: peft.LoraConfig
    r: ${peft_config.r}
    lora_alpha: ${peft_config.lora_alpha}
    target_modules: ${peft_config.target_modules}
    lora_dropout: ${peft_config.lora_dropout}
    bias: ${peft_config.bias}
    task_type: ${peft_config.task_type}
  dropout_ratio: ${dropout_ratio}
  num_labels: ${num_labels}

pretrained_model_name: ${pretrained_model_name}
is_preprocessed: ${is_preprocessed}
custom_data_encoder_path: ${custom_data_encoder_path}
num_labels: ${num_labels}
strategy: ${strategy}
lr: ${lr}
period: ${period}
eta_min: ${eta_min}
interval: step
options: ${options}
target_max_length: ${target_max_length}
target_column_name: ${target_column_name}