_target_: src.datasets.huggingface_dataset.DACONBirdImageDataset
data_path: ${connected_dir}/data
split: ${split.train}
split_ratio: ${split_ratio}
seed: ${seed}
target_column_name: ${target_column_name}
num_devices: ${devices}
batch_size: ${batch_size}
pretrained_model_name: ${pretrained_model_name}
image_size: 256
augmentation_probability: 0.001
augmentations:
  - noise
